services:
  postgresql:
    image: postgres
    restart: always
    shm_size: 128mb
    user: postgres
    volumes:
     - postgres_data:/var/lib/postgresql/data
     - type: bind
       source: ./docker-entrypoint-initdb.d
       target: /docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_root_password
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
     - db_root_password
     - db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
#    ports:
#     - 5432:5432
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8081:8080
  coole-webapp:
    image: davidhuebscher/coole-webapp:latest
    restart: always
    depends_on:
      postgresql:
        condition: service_healthy
        restart: true
    volumes:
     - type: bind
       source: ./certs
       target: /certs
    environment:
      WEBSITE_LOAD_CERTIFICATES: signing-cert,encryption-cert
      WEBSITE_PRIVATE_CERTS_PATH: /certs
      EmailSender__UserName: !!!CHANGEME!!!
      EmailSender__SmtpServer: smtp.gmail.com
      EmailSender__Port: 465
      EmailSender__Password: !!!CHANGEME!!!
      EmailSender__FromName: Coole Webapp
      EmailSender__FromAddress: !!!CHANGEME!!!
      AdministratorsConfiguration__AdministratorEmails__0: !!!CHANGEME!!!
      AdministratorsConfiguration__AdministratorEmails__1: !!!CHANGEME!!!
      AdministratorsConfiguration__AllowedEmailPatterns__0: "*@changeme.net"
      AdministratorsConfiguration__FridgeUserEmails__0: !!!CHANGEME!!!
      DatabaseConfig__DatabaseConnectionString: "Host=postgresql;Port=5432;Database=coole_webapp;Username=coole_webapp;Password=__PASSWORD__;"
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
     - db_password
    ports:
      - 8080:8080

secrets:
  db_password:
    file: db_password.txt
  db_root_password:
    file: db_root_password.txt

volumes:
  postgres_data:
