services:
  postgresql:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
     - postgres_data:/var/lib/postgresql/data
     - type: bind
       source: ./docker-entrypoint-initdb.d
       target: /docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_root_password
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
     - db_root_password
     - db_password
    ports:
     - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

secrets:
  db_password:
    file: db_password.txt
  db_root_password:
    file: db_root_password.txt

volumes:
  postgres_data:
